[capitalcom]
# If it is a demo account
demo = false
# These are required for Capital.com. You can get them from the Capital.com API settings.
user_email = ""
api_key = ""
api_password = ""

[ccxt]
# Default settings for all exchanges if not specified
apiKey = ""
secret = ""
password = ""
# ...anything else your exchange needs
# Exchange specific configuration examples:
# To set exchange specific configurations use sections like:
# [ccxt.binance]
# apiKey = "your_binance_api_key"
# secret = "your_binance_secret"
# 
# [ccxt.kucoin]
# apiKey = "your_kucoin_api_key"
# secret = "your_kucoin_secret"
# password = "your_kucoin_password"
# [ccxt.okex]
# apiKey = "your_okex_api_key"
# secret = "your_okex_secret"
# password = "your_okex_password"
# isTestnet = true    # Add any custom parameter required by the exchange

